export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const SET_LOADING = 'SET_LOADING';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';

export const CREATE_VARIATION = 'CREATE_VARIATION';
export const EDIT_VARIATION = 'EDIT_VARIATION';
export const DELETE_VARIATION = 'DELETE_VARIATION';
export const LIST_VARIATIONS = 'LIST_VARIATIONS';

export const CREATE_OPTION = 'CREATE_OPTION';
export const EDIT_OPTION = 'EDIT_OPTION';
export const DELETE_OPTION = 'DELETE_OPTION';

export const CREATE_BANNER = 'CREATE_BANNER';
export const EDIT_BANNER = 'EDIT_BANNER';
export const DELETE_BANNER = 'DELETE_BANNER';
export const LIST_BANNERS = 'LIST_BANNERS';

export const CREATE_HIGHLIGHT = 'CREATE_HIGHLIGHT';
export const EDIT_HIGHLIGHT = 'EDIT_HIGHLIGHT';
export const DELETE_HIGHLIGHT = 'DELETE_HIGHLIGHT';
export const LIST_HIGHLIGHTS = 'LIST_HIGHLIGHTS';

export const EDIT_STOCK = 'EDIT_STOCK'
