export const EDIT_ORDER = 'EDIT_ORDER';
export const LIST_ORDERS = 'LIST_ORDERS';
export const LOAD_ORDER = 'LOAD_ORDER';
export const ADD_ARRAY_ORDERS = 'ADD_ARRAY_ORDERS';
export const SET_LOADING = 'SET_LOADING';
export const PLAY_NOTIFICATION = 'PLAY_NOTIFICATION';
export const STOP_NOTIFICATION = 'STOP_NOTIFICATION';
export const SET_COMPANY = 'SET_COMPANY';

//chat
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const SET_MESSAGE_AS_SEEN = 'SET_MESSAGE_AS_SEEN';