export const LIST_USERS = 'LIST_USERS';
export const CREATE_USERS = 'CREATE_USERS';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

export const LIST_CUSTOMERS = 'LIST_CUSTOMERS';
export const CREATE_CUSTOMERS = 'CREATE_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
